DROP TABLE EMPLOYEE_ADDRESS; 
DROP TABLE EMPLOYEE_ADDRESS_TYPE; 
DROP TABLE EMPLOYEE_PHONE;
DROP TABLE EMPLOYEE_PHONE_TYPE;
DROP TABLE EMPLOYEE;

DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE EMPLOYEE_ADDRESS_SEQ;
DROP SEQUENCE EMPLOYEE_PHONE_SEQ;
DROP SEQUENCE EMPLOYEE_ADDRESS_TYPE_SEQ;
DROP SEQUENCE EMPLOYEE_PHONE_TYPE_SEQ;