/* ---------------------------DROPS ALL DB OBJECTS------------------------------*/

DROP TABLE EMPLOYEE_ADDRESS; 
DROP TABLE ADDRESS_TYPE; 
DROP TABLE EMPLOYEE_PHONE;
DROP TABLE PHONE_TYPE;
DROP TABLE EMPLOYEE;

DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE EMPLOYEE_ADDRESS_SEQ;
DROP SEQUENCE EMPLOYEE_PHONE_SEQ;
DROP SEQUENCE ADDRESS_TYPE_SEQ;
DROP SEQUENCE PHONE_TYPE_SEQ;


/* ---------------------------TABLES------------------------------*/

CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID   NUMBER(5),
  FIRST_NAME    VARCHAR2(45 BYTE)                     NOT NULL,
  MIDDLE_NAME   VARCHAR2(45 BYTE)                     NOT NULL,
  LAST_NAME     VARCHAR2(45 BYTE)                     NOT NULL,
  GENDER        VARCHAR2(1 BYTE)                      NOT NULL,
  EMAIL_ID      VARCHAR2(45 BYTE)                     NOT NULL
);

CREATE TABLE EMPLOYEE_ADDRESS
(
  EMPLOYEE_ADDRESS_ID       NUMBER(5),
  EMPLOYEE_ID               NUMBER(5),
  ADDRESS_TYPE_ID  NUMBER(5),
  ADDRESSLINE1              VARCHAR2(45 BYTE)        NOT NULL,
  ADDRESSLINE2              VARCHAR2(45 BYTE)        NOT NULL,
  CITY              		VARCHAR2(45 BYTE)        NOT NULL,
  STATE             	 	VARCHAR2(45 BYTE)        NOT NULL,
  ZIPCODE              		VARCHAR2(45 BYTE)        NOT NULL
);

CREATE TABLE ADDRESS_TYPE
(
  ADDRESS_TYPE_ID  		NUMBER(5),
  TYPE         		    VARCHAR2(45 BYTE)        NOT NULL
);

CREATE TABLE EMPLOYEE_PHONE
(
  EMPLOYEE_PHONE_ID         NUMBER                   NOT NULL,
  EMPLOYEE_ID               NUMBER                   NOT NULL,
  PHONE_TYPE_ID    			NUMBER(5),
  PHONE                 	VARCHAR2(20 BYTE)
);

CREATE TABLE PHONE_TYPE
(
  PHONE_TYPE_ID    		NUMBER(5),
  TYPE         		    VARCHAR2(45 BYTE)        NOT NULL
);

/* ---------------------------PK CONSTRAINTS------------------------------*/
 
ALTER TABLE EMPLOYEE ADD (
CONSTRAINT PK_EMPLOYEE
PRIMARY KEY
(EMPLOYEE_ID));

ALTER TABLE EMPLOYEE_ADDRESS ADD (
CONSTRAINT PK_EMPLOYEE_ADDRESS
PRIMARY KEY
(EMPLOYEE_ADDRESS_ID));

ALTER TABLE ADDRESS_TYPE ADD (
CONSTRAINT PK_ADDRESS_TYPE
PRIMARY KEY
(ADDRESS_TYPE_ID));

ALTER TABLE EMPLOYEE_PHONE ADD (
CONSTRAINT PK_EMPLOYEE_PHONE
PRIMARY KEY
(EMPLOYEE_PHONE_ID));

ALTER TABLE PHONE_TYPE ADD (
CONSTRAINT PK_PHONE_TYPE
PRIMARY KEY
(PHONE_TYPE_ID));

/* ---------------------------FK CONSTRAINTS------------------------------*/

ALTER TABLE EMPLOYEE_ADDRESS ADD (
CONSTRAINT FK_EMP_ADD_EMP_ID
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES EMPLOYEE (EMPLOYEE_ID));

ALTER TABLE EMPLOYEE_ADDRESS ADD (
CONSTRAINT FK_EMP_ADD_TYPE_ID
FOREIGN KEY (ADDRESS_TYPE_ID) 
REFERENCES ADDRESS_TYPE (ADDRESS_TYPE_ID));

ALTER TABLE EMPLOYEE_PHONE ADD (
CONSTRAINT FK_EMP_PHONE_EMP_ID
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES EMPLOYEE (EMPLOYEE_ID));

ALTER TABLE EMPLOYEE_PHONE ADD (
CONSTRAINT FK_EMP_PH_TYPE_ID
FOREIGN KEY (PHONE_TYPE_ID) 
REFERENCES PHONE_TYPE (PHONE_TYPE_ID));


/* ---------------------------SEQUENCES------------------------------*/

CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPLOYEE_ADDRESS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPLOYEE_PHONE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADDRESS_TYPE_SEQ START WITH 10 INCREMENT BY 10;
CREATE SEQUENCE PHONE_TYPE_SEQ START WITH 10 INCREMENT BY 10;



/* ---------------------------STATIC DATA------------------------------*/

INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_ID, TYPE) VALUES (ADDRESS_TYPE_SEQ.NEXTVAL, 'PERMANENT');
INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_ID, TYPE) VALUES (ADDRESS_TYPE_SEQ.NEXTVAL, 'PRESENT');
INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_ID, TYPE) VALUES (ADDRESS_TYPE_SEQ.NEXTVAL, 'OFFICE');

INSERT INTO PHONE_TYPE (PHONE_TYPE_ID, TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL, 'OFFICE');
INSERT INTO PHONE_TYPE (PHONE_TYPE_ID, TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL, 'FAX');
INSERT INTO PHONE_TYPE (PHONE_TYPE_ID, TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL, 'HOME');
INSERT INTO PHONE_TYPE (PHONE_TYPE_ID, TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL, 'MOBILE');
INSERT INTO PHONE_TYPE (PHONE_TYPE_ID, TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL, 'OTHER');


COMMIT;


